Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |vb|
      vb.memory = 2048
      vb.cpus = 2
    config.vm.provision "shell",
      inline: "sudo yum update -y && sudo yum install ansible-core tmux -y"
    end
    config.vm.box = "rockylinux/8"
    # Ansible server 1.
    config.vm.define "ansible" do |ansible|
      ansible.vm.hostname = "ansible.dev"
      ansible.vm.network :private_network, ip: "192.168.3.4"
    end
    # Application server 1.
    config.vm.define "node1" do |node1|
        node1.vm.hostname = "node1.dev"
        node1.vm.network :private_network, ip: "192.168.3.5"
      end
    # Node2 server.
    config.vm.define "node2" do |node2|
      node2.vm.hostname = "node2.dev"
      node2.vm.network :private_network, ip: "192.168.3.6"
    end
end   